version: '3.8'

services:
  db:
    image: postgis/postgis:latest
    container_name: runbuddy-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - runbuddy-network

networks:
  runbuddy-network:
    driver: bridge
